name: Test GIT Setup script

on:
  push:
    branches:
      - main

jobs:
  setup-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and run git.sh
        run: |
          SCRIPT_PATH=$(find ${{ github.workspace }} -name "git.sh" -type f)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "git.sh not found!"
            exit 1
          fi
          chmod +x $SCRIPT_PATH
          $SCRIPT_PATH
